[project]
name = "tokenizer"
version = "0.1.0"
description = "A CLI tool that crawls a directory and counts the tokens per filetype"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "openai>=1.63.2",
    "pillow>=11.1.0",
    "tiktoken>=0.9.0",
]
